In [56]:
import pathlib
import chess
import chess.pgn
import chess.engine
import numpy as np
import h5py

In [57]:
pgnGames = list(pathlib.Path('').glob('*.pgn'))

In [58]:
# General space saving algorithms that are often used in chess programming sites

def board_to_arr(board: chess.Board):
    black, white = board.occupied_co

    bitboards = np.array([
        black & board.pawns,
        black & board.knights,
        black & board.bishops,
        black & board.rooks,
        black & board.queens,
        black & board.kings,
        white & board.pawns,
        white & board.knights,
        white & board.bishops,
        white & board.rooks,
        white & board.queens,
        white & board.kings,
    ], dtype=np.uint64)

    return bitboards

def bitboards_to_array(bb: np.ndarray) -> np.ndarray:
    bb = np.asarray(bb, dtype=np.uint64)[:, np.newaxis]
    s = 8 * np.arange(7, -1, -1, dtype=np.uint64)
    b = (bb >> s).astype(np.uint8)
    b = np.unpackbits(b, bitorder="little")
    return b.reshape(-1, 8, 8)


In [59]:
engine = chess.engine.SimpleEngine.popen_uci("engines/stockfish-macos-x86-64-bmi2")

def convert_to_winrate(acpl):
    
    return (50 + 50 * (2 / (1 + np.exp(-0.00368208 * acpl)) - 1)) * 0.01

def evaluate_game(game, think_time=0.1, verbose=False):
    
    single_game = []
    evaluations = []
    
    board = game.board()

    for move in game.mainline_moves():
    
        # Evaluate the current position 
        result = engine.analyse(board, chess.engine.Limit(time=think_time))
        
        if result['score'].turn: 
            try:
                objective_eval = result['score'].relative.cp
                evaluations.append(convert_to_winrate(objective_eval))
            except:
                if result['score'].relative.moves > 0:
                    evaluations.append(1)
                else:
                    evaluations.append(0)
        else:
            try:
                objective_eval = result['score'].relative.cp * -1
                evaluations.append(convert_to_winrate(objective_eval))
            except:
                if result['score'].relative.moves < 0:
                    evaluations.append(1)
                else:
                    evaluations.append(0)       
        
        # Push the game state to new
        board.push_uci(move.uci())
        single_game.append(board_to_arr(board))
    
    # Evaluate final position once more to find accuracy of last move
    result = engine.analyse(board, chess.engine.Limit(time=think_time))
    evaluations.append(convert_to_winrate(objective_eval))
    if verbose:
        print(evaluations)
    
    winrate_diff = [abs(x - evaluations[i - 1]) for i, x in enumerate(evaluations)][1:]

    return single_game, winrate_diff
    

### Generate Dataset

In [60]:
X = []
y = []

for g in range(len(pgnGames)):
    pgn = open(pgnGames[g])
    
    for k in range(5000):  # 190,000 assures all games are looked at.
        
        try:
            game = chess.pgn.read_game(pgn)

            board_history, winrate_history = evaluate_game(game, think_time=0.025, verbose=False)
            X += board_history
            y += winrate_history
            print(f"{k+1} games analyzed, dataset size {len(X)}")
        except Exception as e:
            print(f"{e}")
            pass
          

1 games analyzed, dataset size 55
2 games analyzed, dataset size 192
3 games analyzed, dataset size 251
4 games analyzed, dataset size 383
5 games analyzed, dataset size 481
6 games analyzed, dataset size 572
7 games analyzed, dataset size 625
8 games analyzed, dataset size 670
9 games analyzed, dataset size 695
10 games analyzed, dataset size 816
11 games analyzed, dataset size 869
12 games analyzed, dataset size 991
13 games analyzed, dataset size 1059
14 games analyzed, dataset size 1115
15 games analyzed, dataset size 1210
16 games analyzed, dataset size 1302
17 games analyzed, dataset size 1372
18 games analyzed, dataset size 1432
19 games analyzed, dataset size 1507
20 games analyzed, dataset size 1583
21 games analyzed, dataset size 1663
22 games analyzed, dataset size 1707
23 games analyzed, dataset size 1792
24 games analyzed, dataset size 1949
25 games analyzed, dataset size 2001
26 games analyzed, dataset size 2069
27 games analyzed, dataset size 2136
28 games analyzed, data

218 games analyzed, dataset size 18287
219 games analyzed, dataset size 18362
220 games analyzed, dataset size 18448
221 games analyzed, dataset size 18520
222 games analyzed, dataset size 18578
223 games analyzed, dataset size 18683
224 games analyzed, dataset size 18735
225 games analyzed, dataset size 18836
226 games analyzed, dataset size 18933
227 games analyzed, dataset size 18992
228 games analyzed, dataset size 19062
229 games analyzed, dataset size 19115
230 games analyzed, dataset size 19168
231 games analyzed, dataset size 19426
232 games analyzed, dataset size 19536
233 games analyzed, dataset size 19642
234 games analyzed, dataset size 19705
235 games analyzed, dataset size 19785
236 games analyzed, dataset size 19877
237 games analyzed, dataset size 19936
238 games analyzed, dataset size 19970
239 games analyzed, dataset size 20058
240 games analyzed, dataset size 20128
241 games analyzed, dataset size 20184
242 games analyzed, dataset size 20241
243 games analyzed, datas

429 games analyzed, dataset size 36170
430 games analyzed, dataset size 36251
431 games analyzed, dataset size 36336
432 games analyzed, dataset size 36385
433 games analyzed, dataset size 36542
434 games analyzed, dataset size 36586
435 games analyzed, dataset size 36678
436 games analyzed, dataset size 36747
437 games analyzed, dataset size 36844
438 games analyzed, dataset size 36932
439 games analyzed, dataset size 37016
440 games analyzed, dataset size 37099
441 games analyzed, dataset size 37121
442 games analyzed, dataset size 37258
443 games analyzed, dataset size 37318
444 games analyzed, dataset size 37375
445 games analyzed, dataset size 37468
446 games analyzed, dataset size 37580
447 games analyzed, dataset size 37719
448 games analyzed, dataset size 37771
449 games analyzed, dataset size 37876
450 games analyzed, dataset size 37971
451 games analyzed, dataset size 38121
452 games analyzed, dataset size 38235
453 games analyzed, dataset size 38291
454 games analyzed, datas

640 games analyzed, dataset size 53150
641 games analyzed, dataset size 53215
642 games analyzed, dataset size 53299
643 games analyzed, dataset size 53372
644 games analyzed, dataset size 53422
645 games analyzed, dataset size 53513
646 games analyzed, dataset size 53551
647 games analyzed, dataset size 53673
648 games analyzed, dataset size 53721
649 games analyzed, dataset size 53877
650 games analyzed, dataset size 53982
651 games analyzed, dataset size 54047
652 games analyzed, dataset size 54061
653 games analyzed, dataset size 54212
654 games analyzed, dataset size 54282
655 games analyzed, dataset size 54380
656 games analyzed, dataset size 54497
657 games analyzed, dataset size 54577
658 games analyzed, dataset size 54647
659 games analyzed, dataset size 54722
660 games analyzed, dataset size 54841
661 games analyzed, dataset size 54953
662 games analyzed, dataset size 55115
663 games analyzed, dataset size 55248
664 games analyzed, dataset size 55352
665 games analyzed, datas

851 games analyzed, dataset size 71901
852 games analyzed, dataset size 72068
853 games analyzed, dataset size 72112
854 games analyzed, dataset size 72171
855 games analyzed, dataset size 72264
856 games analyzed, dataset size 72404
857 games analyzed, dataset size 72518
858 games analyzed, dataset size 72575
859 games analyzed, dataset size 72600
860 games analyzed, dataset size 72669
861 games analyzed, dataset size 72740
862 games analyzed, dataset size 72864
863 games analyzed, dataset size 72948
864 games analyzed, dataset size 73024
865 games analyzed, dataset size 73109
866 games analyzed, dataset size 73157
867 games analyzed, dataset size 73274
868 games analyzed, dataset size 73401
869 games analyzed, dataset size 73517
870 games analyzed, dataset size 73585
871 games analyzed, dataset size 73617
872 games analyzed, dataset size 73691
873 games analyzed, dataset size 73806
874 games analyzed, dataset size 73891
875 games analyzed, dataset size 73954
876 games analyzed, datas

1060 games analyzed, dataset size 88808
1061 games analyzed, dataset size 88922
1062 games analyzed, dataset size 88981
1063 games analyzed, dataset size 89040
1064 games analyzed, dataset size 89153
1065 games analyzed, dataset size 89236
1066 games analyzed, dataset size 89322
1067 games analyzed, dataset size 89386
1068 games analyzed, dataset size 89431
1069 games analyzed, dataset size 89523
1070 games analyzed, dataset size 89600
1071 games analyzed, dataset size 89639
1072 games analyzed, dataset size 89687
1073 games analyzed, dataset size 89763
1074 games analyzed, dataset size 89853
1075 games analyzed, dataset size 89897
1076 games analyzed, dataset size 89944
1077 games analyzed, dataset size 90064
1078 games analyzed, dataset size 90227
1079 games analyzed, dataset size 90338
1080 games analyzed, dataset size 90404
1081 games analyzed, dataset size 90503
1082 games analyzed, dataset size 90583
1083 games analyzed, dataset size 90619
1084 games analyzed, dataset size 90785


1264 games analyzed, dataset size 105362
1265 games analyzed, dataset size 105442
1266 games analyzed, dataset size 105499
1267 games analyzed, dataset size 105570
1268 games analyzed, dataset size 105595
1269 games analyzed, dataset size 105670
1270 games analyzed, dataset size 105701
1271 games analyzed, dataset size 105766
1272 games analyzed, dataset size 105941
1273 games analyzed, dataset size 105986
1274 games analyzed, dataset size 106138
1275 games analyzed, dataset size 106184
1276 games analyzed, dataset size 106237
1277 games analyzed, dataset size 106387
1278 games analyzed, dataset size 106471
1279 games analyzed, dataset size 106507
1280 games analyzed, dataset size 106581
1281 games analyzed, dataset size 106673
1282 games analyzed, dataset size 106821
1283 games analyzed, dataset size 106879
1284 games analyzed, dataset size 106932
1285 games analyzed, dataset size 107034
1286 games analyzed, dataset size 107126
1287 games analyzed, dataset size 107236
1288 games analy

1464 games analyzed, dataset size 122844
1465 games analyzed, dataset size 122936
1466 games analyzed, dataset size 123009
1467 games analyzed, dataset size 123135
1468 games analyzed, dataset size 123168
1469 games analyzed, dataset size 123219
1470 games analyzed, dataset size 123357
1471 games analyzed, dataset size 123436
1472 games analyzed, dataset size 123522
1473 games analyzed, dataset size 123594
1474 games analyzed, dataset size 123662
1475 games analyzed, dataset size 123830
1476 games analyzed, dataset size 123901
1477 games analyzed, dataset size 123982
1478 games analyzed, dataset size 124116
1479 games analyzed, dataset size 124268
1480 games analyzed, dataset size 124328
1481 games analyzed, dataset size 124379
1482 games analyzed, dataset size 124415
1483 games analyzed, dataset size 124491
1484 games analyzed, dataset size 124608
1485 games analyzed, dataset size 124665
1486 games analyzed, dataset size 124769
1487 games analyzed, dataset size 124816
1488 games analy

1664 games analyzed, dataset size 139157
1665 games analyzed, dataset size 139218
1666 games analyzed, dataset size 139298
1667 games analyzed, dataset size 139379
1668 games analyzed, dataset size 139453
1669 games analyzed, dataset size 139514
1670 games analyzed, dataset size 139603
1671 games analyzed, dataset size 139653
1672 games analyzed, dataset size 139742
1673 games analyzed, dataset size 139799
1674 games analyzed, dataset size 139871
1675 games analyzed, dataset size 139903
1676 games analyzed, dataset size 140012
1677 games analyzed, dataset size 140112
1678 games analyzed, dataset size 140193
1679 games analyzed, dataset size 140302
1680 games analyzed, dataset size 140381
1681 games analyzed, dataset size 140499
1682 games analyzed, dataset size 140546
1683 games analyzed, dataset size 140610
1684 games analyzed, dataset size 140657
1685 games analyzed, dataset size 140777
1686 games analyzed, dataset size 140879
1687 games analyzed, dataset size 140948
1688 games analy

1864 games analyzed, dataset size 156035
1865 games analyzed, dataset size 156188
1866 games analyzed, dataset size 156294
1867 games analyzed, dataset size 156380
1868 games analyzed, dataset size 156461
1869 games analyzed, dataset size 156511
1870 games analyzed, dataset size 156542
1871 games analyzed, dataset size 156682
1872 games analyzed, dataset size 156774
1873 games analyzed, dataset size 156795
1874 games analyzed, dataset size 156920
1875 games analyzed, dataset size 156995
1876 games analyzed, dataset size 157055
1877 games analyzed, dataset size 157120
1878 games analyzed, dataset size 157295
1879 games analyzed, dataset size 157411
1880 games analyzed, dataset size 157530
1881 games analyzed, dataset size 157646
1882 games analyzed, dataset size 157680
1883 games analyzed, dataset size 157758
1884 games analyzed, dataset size 157859
1885 games analyzed, dataset size 158019
1886 games analyzed, dataset size 158102
1887 games analyzed, dataset size 158189
1888 games analy

2064 games analyzed, dataset size 172015
2065 games analyzed, dataset size 172073
2066 games analyzed, dataset size 172134
2067 games analyzed, dataset size 172185
2068 games analyzed, dataset size 172280
2069 games analyzed, dataset size 172371
2070 games analyzed, dataset size 172445
2071 games analyzed, dataset size 172509
2072 games analyzed, dataset size 172549
2073 games analyzed, dataset size 172638
2074 games analyzed, dataset size 172731
2075 games analyzed, dataset size 172830
2076 games analyzed, dataset size 172903
2077 games analyzed, dataset size 172945
2078 games analyzed, dataset size 173024
2079 games analyzed, dataset size 173123
2080 games analyzed, dataset size 173218
2081 games analyzed, dataset size 173522
2082 games analyzed, dataset size 173563
2083 games analyzed, dataset size 173731
2084 games analyzed, dataset size 173814
2085 games analyzed, dataset size 173907
2086 games analyzed, dataset size 174007
2087 games analyzed, dataset size 174105
2088 games analy

2264 games analyzed, dataset size 188399
2265 games analyzed, dataset size 188512
2266 games analyzed, dataset size 188587
2267 games analyzed, dataset size 188717
2268 games analyzed, dataset size 188764
2269 games analyzed, dataset size 188821
2270 games analyzed, dataset size 188909
2271 games analyzed, dataset size 188961
2272 games analyzed, dataset size 189073
2273 games analyzed, dataset size 189128
2274 games analyzed, dataset size 189156
2275 games analyzed, dataset size 189201
2276 games analyzed, dataset size 189238
2277 games analyzed, dataset size 189300
2278 games analyzed, dataset size 189412
2279 games analyzed, dataset size 189507
2280 games analyzed, dataset size 189602
2281 games analyzed, dataset size 189803
2282 games analyzed, dataset size 189835
2283 games analyzed, dataset size 189928
2284 games analyzed, dataset size 189975
2285 games analyzed, dataset size 190102
2286 games analyzed, dataset size 190169
2287 games analyzed, dataset size 190261
2288 games analy

2464 games analyzed, dataset size 204235
2465 games analyzed, dataset size 204311
2466 games analyzed, dataset size 204397
2467 games analyzed, dataset size 204459
2468 games analyzed, dataset size 204570
2469 games analyzed, dataset size 204606
2470 games analyzed, dataset size 204660
2471 games analyzed, dataset size 204689
2472 games analyzed, dataset size 204754
2473 games analyzed, dataset size 204840
2474 games analyzed, dataset size 204933
2475 games analyzed, dataset size 204974
2476 games analyzed, dataset size 205064
2477 games analyzed, dataset size 205156
2478 games analyzed, dataset size 205214
2479 games analyzed, dataset size 205324
2480 games analyzed, dataset size 205420
2481 games analyzed, dataset size 205489
2482 games analyzed, dataset size 205559
2483 games analyzed, dataset size 205618
2484 games analyzed, dataset size 205762
2485 games analyzed, dataset size 205883
2486 games analyzed, dataset size 205989
2487 games analyzed, dataset size 206099
2488 games analy

2664 games analyzed, dataset size 220583
2665 games analyzed, dataset size 220704
2666 games analyzed, dataset size 220787
2667 games analyzed, dataset size 220891
2668 games analyzed, dataset size 220946
2669 games analyzed, dataset size 221004
2670 games analyzed, dataset size 221039
2671 games analyzed, dataset size 221123
2672 games analyzed, dataset size 221163
2673 games analyzed, dataset size 221289
2674 games analyzed, dataset size 221372
2675 games analyzed, dataset size 221409
2676 games analyzed, dataset size 221474
2677 games analyzed, dataset size 221551
2678 games analyzed, dataset size 221597
2679 games analyzed, dataset size 221681
2680 games analyzed, dataset size 221731
2681 games analyzed, dataset size 221850
2682 games analyzed, dataset size 221952
2683 games analyzed, dataset size 222032
2684 games analyzed, dataset size 222177
2685 games analyzed, dataset size 222246
2686 games analyzed, dataset size 222301
2687 games analyzed, dataset size 222399
2688 games analy

2864 games analyzed, dataset size 236471
2865 games analyzed, dataset size 236528
2866 games analyzed, dataset size 236623
2867 games analyzed, dataset size 236775
2868 games analyzed, dataset size 236868
2869 games analyzed, dataset size 236920
2870 games analyzed, dataset size 236990
2871 games analyzed, dataset size 237104
2872 games analyzed, dataset size 237179
2873 games analyzed, dataset size 237248
2874 games analyzed, dataset size 237347
2875 games analyzed, dataset size 237399
2876 games analyzed, dataset size 237529
2877 games analyzed, dataset size 237610
2878 games analyzed, dataset size 237691
2879 games analyzed, dataset size 237820
2880 games analyzed, dataset size 237930
2881 games analyzed, dataset size 237989
2882 games analyzed, dataset size 238098
2883 games analyzed, dataset size 238148
2884 games analyzed, dataset size 238201
2885 games analyzed, dataset size 238288
2886 games analyzed, dataset size 238395
2887 games analyzed, dataset size 238464
2888 games analy

3064 games analyzed, dataset size 253268
3065 games analyzed, dataset size 253349
3066 games analyzed, dataset size 253459
3067 games analyzed, dataset size 253494
3068 games analyzed, dataset size 253548
3069 games analyzed, dataset size 253621
3070 games analyzed, dataset size 253666
3071 games analyzed, dataset size 253732
3072 games analyzed, dataset size 253842
3073 games analyzed, dataset size 253927
3074 games analyzed, dataset size 254049
3075 games analyzed, dataset size 254146
3076 games analyzed, dataset size 254235
3077 games analyzed, dataset size 254281
3078 games analyzed, dataset size 254417
3079 games analyzed, dataset size 254460
3080 games analyzed, dataset size 254671
3081 games analyzed, dataset size 254739
3082 games analyzed, dataset size 254776
3083 games analyzed, dataset size 254891
3084 games analyzed, dataset size 254949
3085 games analyzed, dataset size 255044
3086 games analyzed, dataset size 255139
3087 games analyzed, dataset size 255225
3088 games analy

3264 games analyzed, dataset size 270054
3265 games analyzed, dataset size 270163
3266 games analyzed, dataset size 270209
3267 games analyzed, dataset size 270277
3268 games analyzed, dataset size 270358
3269 games analyzed, dataset size 270484
3270 games analyzed, dataset size 270586
3271 games analyzed, dataset size 270638
3272 games analyzed, dataset size 270712
3273 games analyzed, dataset size 270830
3274 games analyzed, dataset size 270956
3275 games analyzed, dataset size 271069
3276 games analyzed, dataset size 271098
3277 games analyzed, dataset size 271189
3278 games analyzed, dataset size 271258
3279 games analyzed, dataset size 271369
3280 games analyzed, dataset size 271486
3281 games analyzed, dataset size 271533
3282 games analyzed, dataset size 271715
3283 games analyzed, dataset size 271762
3284 games analyzed, dataset size 271842
3285 games analyzed, dataset size 271856
3286 games analyzed, dataset size 271909
3287 games analyzed, dataset size 271987
3288 games analy

3464 games analyzed, dataset size 286556
3465 games analyzed, dataset size 286644
3466 games analyzed, dataset size 286805
3467 games analyzed, dataset size 286877
3468 games analyzed, dataset size 286952
3469 games analyzed, dataset size 287026
3470 games analyzed, dataset size 287065
3471 games analyzed, dataset size 287167
3472 games analyzed, dataset size 287217
3473 games analyzed, dataset size 287305
3474 games analyzed, dataset size 287362
3475 games analyzed, dataset size 287493
3476 games analyzed, dataset size 287586
3477 games analyzed, dataset size 287674
3478 games analyzed, dataset size 287728
3479 games analyzed, dataset size 287771
3480 games analyzed, dataset size 287834
3481 games analyzed, dataset size 287888
3482 games analyzed, dataset size 287979
3483 games analyzed, dataset size 288073
3484 games analyzed, dataset size 288127
3485 games analyzed, dataset size 288174
3486 games analyzed, dataset size 288323
3487 games analyzed, dataset size 288396
3488 games analy

3664 games analyzed, dataset size 302641
3665 games analyzed, dataset size 302743
3666 games analyzed, dataset size 302858
3667 games analyzed, dataset size 302960
3668 games analyzed, dataset size 303016
3669 games analyzed, dataset size 303047
3670 games analyzed, dataset size 303074
3671 games analyzed, dataset size 303163
3672 games analyzed, dataset size 303254
3673 games analyzed, dataset size 303284
3674 games analyzed, dataset size 303342
3675 games analyzed, dataset size 303456
3676 games analyzed, dataset size 303606
3677 games analyzed, dataset size 303775
3678 games analyzed, dataset size 303834
3679 games analyzed, dataset size 303884
3680 games analyzed, dataset size 303988
3681 games analyzed, dataset size 304080
3682 games analyzed, dataset size 304162
3683 games analyzed, dataset size 304231
3684 games analyzed, dataset size 304329
3685 games analyzed, dataset size 304406
3686 games analyzed, dataset size 304493
3687 games analyzed, dataset size 304550
3688 games analy

3864 games analyzed, dataset size 319825
3865 games analyzed, dataset size 319965
3866 games analyzed, dataset size 320066
3867 games analyzed, dataset size 320117
3868 games analyzed, dataset size 320215
3869 games analyzed, dataset size 320286
3870 games analyzed, dataset size 320354
3871 games analyzed, dataset size 320496
3872 games analyzed, dataset size 320571
3873 games analyzed, dataset size 320610
3874 games analyzed, dataset size 320689
3875 games analyzed, dataset size 320756
3876 games analyzed, dataset size 320828
3877 games analyzed, dataset size 320894
3878 games analyzed, dataset size 320944
3879 games analyzed, dataset size 320981
3880 games analyzed, dataset size 321012
3881 games analyzed, dataset size 321150
3882 games analyzed, dataset size 321204
3883 games analyzed, dataset size 321275
3884 games analyzed, dataset size 321372
3885 games analyzed, dataset size 321453
3886 games analyzed, dataset size 321502
3887 games analyzed, dataset size 321554
3888 games analy

4064 games analyzed, dataset size 335111
4065 games analyzed, dataset size 335154
4066 games analyzed, dataset size 335269
4067 games analyzed, dataset size 335332
4068 games analyzed, dataset size 335424
4069 games analyzed, dataset size 335492
4070 games analyzed, dataset size 335603
4071 games analyzed, dataset size 335690
4072 games analyzed, dataset size 335738
4073 games analyzed, dataset size 335749
4074 games analyzed, dataset size 335825
4075 games analyzed, dataset size 335875
4076 games analyzed, dataset size 335944
4077 games analyzed, dataset size 335979
4078 games analyzed, dataset size 336039
4079 games analyzed, dataset size 336089
4080 games analyzed, dataset size 336191
4081 games analyzed, dataset size 336248
4082 games analyzed, dataset size 336283
4083 games analyzed, dataset size 336350
4084 games analyzed, dataset size 336495
4085 games analyzed, dataset size 336562
4086 games analyzed, dataset size 336644
4087 games analyzed, dataset size 336750
4088 games analy

4264 games analyzed, dataset size 351210
4265 games analyzed, dataset size 351273
4266 games analyzed, dataset size 351390
4267 games analyzed, dataset size 351468
4268 games analyzed, dataset size 351520
4269 games analyzed, dataset size 351634
4270 games analyzed, dataset size 351682
4271 games analyzed, dataset size 351800
4272 games analyzed, dataset size 351841
4273 games analyzed, dataset size 351923
4274 games analyzed, dataset size 352046
4275 games analyzed, dataset size 352169
4276 games analyzed, dataset size 352311
4277 games analyzed, dataset size 352407
4278 games analyzed, dataset size 352500
4279 games analyzed, dataset size 352575
4280 games analyzed, dataset size 352682
4281 games analyzed, dataset size 352772
4282 games analyzed, dataset size 352901
4283 games analyzed, dataset size 352933
4284 games analyzed, dataset size 352984
4285 games analyzed, dataset size 353049
4286 games analyzed, dataset size 353095
4287 games analyzed, dataset size 353158
4288 games analy

4464 games analyzed, dataset size 367000
4465 games analyzed, dataset size 367071
4466 games analyzed, dataset size 367132
4467 games analyzed, dataset size 367215
4468 games analyzed, dataset size 367312
4469 games analyzed, dataset size 367352
4470 games analyzed, dataset size 367440
4471 games analyzed, dataset size 367520
4472 games analyzed, dataset size 367608
4473 games analyzed, dataset size 367691
4474 games analyzed, dataset size 367740
4475 games analyzed, dataset size 367798
4476 games analyzed, dataset size 367852
4477 games analyzed, dataset size 367958
4478 games analyzed, dataset size 368016
4479 games analyzed, dataset size 368067
4480 games analyzed, dataset size 368142
4481 games analyzed, dataset size 368245
4482 games analyzed, dataset size 368288
4483 games analyzed, dataset size 368371
4484 games analyzed, dataset size 368494
4485 games analyzed, dataset size 368581
4486 games analyzed, dataset size 368635
4487 games analyzed, dataset size 368674
4488 games analy

4664 games analyzed, dataset size 383328
4665 games analyzed, dataset size 383395
4666 games analyzed, dataset size 383475
4667 games analyzed, dataset size 383556
4668 games analyzed, dataset size 383630
4669 games analyzed, dataset size 383734
4670 games analyzed, dataset size 383813
4671 games analyzed, dataset size 383908
4672 games analyzed, dataset size 384014
4673 games analyzed, dataset size 384133
4674 games analyzed, dataset size 384201
4675 games analyzed, dataset size 384344
4676 games analyzed, dataset size 384469
4677 games analyzed, dataset size 384524
4678 games analyzed, dataset size 384593
4679 games analyzed, dataset size 384643
4680 games analyzed, dataset size 384667
4681 games analyzed, dataset size 384683
4682 games analyzed, dataset size 384757
4683 games analyzed, dataset size 384809
4684 games analyzed, dataset size 384862
4685 games analyzed, dataset size 384911
4686 games analyzed, dataset size 385010
4687 games analyzed, dataset size 385049
4688 games analy

4864 games analyzed, dataset size 399884
4865 games analyzed, dataset size 399951
4866 games analyzed, dataset size 400016
4867 games analyzed, dataset size 400048
4868 games analyzed, dataset size 400105
4869 games analyzed, dataset size 400185
4870 games analyzed, dataset size 400296
4871 games analyzed, dataset size 400377
4872 games analyzed, dataset size 400457
4873 games analyzed, dataset size 400547
4874 games analyzed, dataset size 400647
4875 games analyzed, dataset size 400705
4876 games analyzed, dataset size 400827
4877 games analyzed, dataset size 400902
4878 games analyzed, dataset size 401004
4879 games analyzed, dataset size 401062
4880 games analyzed, dataset size 401191
4881 games analyzed, dataset size 401300
4882 games analyzed, dataset size 401391
4883 games analyzed, dataset size 401507
4884 games analyzed, dataset size 401636
4885 games analyzed, dataset size 401698
4886 games analyzed, dataset size 401736
4887 games analyzed, dataset size 401858
4888 games analy

In [61]:
X = np.dstack(X)
y = np.array(y, dtype='float32')
X = np.rollaxis(X, -1).reshape(-1, 12)

In [62]:
X.shape, y.shape

((411343, 12), (411343,))

In [63]:
print(bitboards_to_array(X[0]))

[[[0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 1 0 0 0 0 1 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 1 0 0 1 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[1 0 0 0 0 0 0 1]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 1 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 1 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 0 0

In [64]:
with h5py.File('positions.h5', 'w') as hf:
    hf.create_dataset("X", data=X, compression='gzip', compression_opts=5)
    hf.create_dataset("y", data=y, compression='gzip', compression_opts=5)

In [65]:
print(max(y))

1.0


In [66]:
sorted(y)[::-1][:50]

[1.0,
 1.0,
 1.0,
 1.0,
 0.9660068,
 0.9660068,
 0.96271896,
 0.9456945,
 0.93609005,
 0.92987823,
 0.92258793,
 0.91345197,
 0.91345197,
 0.91205704,
 0.8967275,
 0.8967275,
 0.89361805,
 0.8867819,
 0.87760174,
 0.87561035,
 0.87399733,
 0.86821014,
 0.86407167,
 0.86219907,
 0.8596773,
 0.85955316,
 0.8595424,
 0.85910803,
 0.8586618,
 0.8586618,
 0.85549045,
 0.8536745,
 0.85283273,
 0.85193205,
 0.8513598,
 0.8513598,
 0.8472463,
 0.84228736,
 0.84228736,
 0.8398263,
 0.8398263,
 0.83898693,
 0.83531815,
 0.83531815,
 0.8322565,
 0.8322565,
 0.8322565,
 0.8296706,
 0.82731193,
 0.82652575]